### ISSUE TITLE
Precision of the measured performance

### ISSUE THREAD

**Issue by HaFred** [ycjungSubhuman/cyobj#1]
Hi thanks for contributing this pkg to the community. Just curious how did you come up with the measured performance of `cvobj` vs. `c++`?
>> cyobj: 465.68751335144043 ms

It seems like the precision of your result is down to more than 1e-10 of miliseconds, which I believe is already way lower than the processors' clock cycle. Thank you again.

**Comment by ycjungSubhuman** [comment]
Hi. I have run multiple reads and simply divided overall time by the number of reads. As you suggested, the precision of the reported value is not correct.

[d0b513d](https://github.com/ycjungSubhuman/cyobj/commit/d0b513d4a7398dfba58bd6c795e3963c789ade15) fixes this issue. Thanks.
